server:
  port: ${GATEWAY_API_PORT}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_HOST}:${USER_SERVICE_PORT}
          predicates:
            - Path=/api/users/**
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"